In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('moviereviews.csv')

In [4]:
df.head()

  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [5]:
df.isnull().sum()

label      0
review    35
dtype: int64

In [6]:
df = df.dropna()

In [7]:
df[df['review'] == ""]

Empty DataFrame
Columns: [label, review]
Index: []

In [8]:
df['review'].str.isspace().sum()

np.int64(27)

In [9]:
df[df['review'].str.isspace()]

     label review
57     neg
71     pos
147    pos
151    pos
283    pos
307    pos
313    neg
323    pos
343    pos
351    neg
427    pos
501    neg
633    pos
675    neg
815    neg
851    neg
977    neg
1079   neg
1299   pos
1455   neg
1493   pos
1525   neg
1531   neg
1763   neg
1851   neg
1905   pos
1993   pos

In [10]:
df = df[~df['review'].str.isspace()]

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 1938 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   1938 non-null   str
 1   review  1938 non-null   str
dtypes: str(2)
memory usage: 45.4 KB

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 1938 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   1938 non-null   str
 1   review  1938 non-null   str
dtypes: str(2)
memory usage: 45.4 KB

In [13]:
df['label'].value_counts()

label
neg    969
pos    969
Name: count, dtype: int64

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv = CountVectorizer(stop_words="english")

In [16]:
matrix = cv.fit_transform(df[df['label'] == 'neg']['review'])

In [17]:
cv.get_feature_names_out()

array(['00', '000', '007', ..., 'zwick', 'zwigoff', 'zzzzzzz'],
      shape=(27473,), dtype=object)

In [33]:
matrix.sum(axis = 0).tolist()[0]
freqs = zip(cv.get_feature_names_out(),matrix.sum(axis = 0).tolist()[0])
print("Top 20 words used for Negative reviews.")
print(sorted(freqs, key=lambda x: -x[1])[:20])

Top 20 words used for Negative reviews.
[('film', 5002), ('movie', 2389), ('like', 1721), ('just', 1273), ('story', 1199), ('good', 1193), ('time', 1175), ('character', 1037), ('life', 1032), ('characters', 957), ('way', 864), ('films', 851), ('does', 828), ('best', 788), ('people', 769), ('make', 764), ('little', 751), ('really', 731), ('man', 728), ('new', 702)]

In [34]:
matrix = cv.fit_transform(df[df['label'] == 'pos']['review'])
#matrix.sum(axis = 0).tolist()[0]
freqs = zip(cv.get_feature_names_out(),matrix.sum(axis = 0).tolist()[0])
# [("00", 7), ("000", 60) , ....]
# sort from largest to smallest
print("Top 20 words used for Negative reviews.")
print(sorted(freqs, key=lambda x: -x[1])[:20])

Top 20 words used for Negative reviews.
[('film', 5002), ('movie', 2389), ('like', 1721), ('just', 1273), ('story', 1199), ('good', 1193), ('time', 1175), ('character', 1037), ('life', 1032), ('characters', 957), ('way', 864), ('films', 851), ('does', 828), ('best', 788), ('people', 769), ('make', 764), ('little', 751), ('really', 731), ('man', 728), ('new', 702)]

In [35]:
from sklearn.model_selection import train_test_split
X = df["review"]
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

In [37]:
pipe = Pipeline([('tfidf', TfidfVectorizer()), ('NB', MultinomialNB())])

In [38]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('NB', MultinomialNB())])

In [39]:
from sklearn.metrics import ConfusionMatrixDisplay, classification_report

In [40]:
preds = pipe.predict(X_test)

In [41]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

         neg       0.75      0.92      0.83       191
         pos       0.90      0.70      0.79       197

    accuracy                           0.81       388
   macro avg       0.83      0.81      0.81       388
weighted avg       0.83      0.81      0.81       388